version: '3'

services:
  stateless-auth-api:
    container_name: stateless-auth-api
    build:
      context: "./stateless-auth-api"
      dockerfile: Dockerfile
    image: stateless-auth
    environment:
      DB_HOST: stateless-auth-db
      DB_PORT: 5432
      DB_NAME: auth-db
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - stateless-auth
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - stateless-auth-db

  stateless-auth-db:
    container_name: stateless-auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - stateless-auth
    ports:
      - "5432:5432"

  stateless-any-api:
    container_name: stateless-any-api
    build:
      context: "./stateless-any-api"
      dockerfile: Dockerfile
    image: stateless-any
    networks:
      - stateless-auth
    ports:
      - "8081:8081"
    volumes:
      - ./:/app

networks:
  stateless-auth:
    driver: bridge